name: financial_tool
channels:
  - conda-forge
dependencies:
  # run
  - matplotlib ~= 3.3
  - pandas ~= 1.3
  # build/test
  - yaml ~= 0.2
  - pyyaml
  # notebooks
  - jupyterlab ~= 3.0
  # pip
  - pip >= 20
  - pip:
      - shap >=0.34,<0.40
  #yfinance
  - yfinance ~= 0.2.3